### PR TITLE
Fixes #1314 : Include all the invocation in mock verification error message

### LINKED ISSUE #1314: Undesired invocation message improvements
Let’s take a look at the following code.

```kotlin
package whatever

import org.junit.Test
import org.mockito.Mockito

class MultipleUndesiredInvocations {

    interface Inner {
        fun call()
    }

    interface SideEffect {
        fun call()

        class Impl(private val inner: Inner) : SideEffect {
            override fun call() = inner.call()
        }
    }

    interface Outer {
        fun call()

        class Impl(private val inner: Inner, sideEffect: SideEffect) : Outer {

            init {
                sideEffect.call()
            }

            override fun call() {
                inner.call()
            }
        }
    }

    @Test
    fun test() {
        val inner = Mockito.mock(Inner::class.java)
        val sideEffect = SideEffect.Impl(inner)
        val outer = Outer.Impl(inner, sideEffect)

        outer.call()

        Mockito.verify(inner).call()
    }
}
```
The `test` will fail, of course. The following message will be shown.
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
inner.call();
Wanted 1 time:
-> at whatever.MultipleUndesiredInvocations.test(MultipleUndesiredInvocations.kt:43)
But was 2 times. Undesired invocation:
-> at whatever.MultipleUndesiredInvocations$Outer$Impl.call(MultipleUndesiredInvocations.kt:30)
```
It is kind of fine, but the undesired call (for me) is actually inside the `SideEffect` class.

Is it possible to extend the message to show all undesired invocations somehow? It would be extremely helpful when debugging failed tests similar to the sample above — i. e. when a side-effect calls the target object.

### PR DESCRIPTION
**Pull request by SeriyBg**
Have changes the verify error message to include all the invocation instead of including just one undesired invocation.
Previously we have message like:
```
Wanted 1 time:
-> at ...
But was 2 times. Undesired invocation:
-> at ...
```
This PR changes it to 
```
Wanted 1 time:
-> at ...
But was 2 times:
-> at ...
-> at ...
```
To make the error message consistent the similar changes was made for too little invocations case.
The message:
```
Wanted 3 times:
-> at ...
But was 2 times:
-> at ...
```
changed to:
```
Wanted 3 times:
-> at ...
But was 2 times:
-> at ...
-> at ...
```

### CODE REVIEW

**Comment by mockitoguy** [comment]
Nice contribution! We will try to review in the next couple of days.

File: src/main/java/org/mockito/internal/exceptions/Reporter.java [hunk 1]
```diff
@@ -5,9 +5,27 @@
...
+import org.mockito.exceptions.misusing.MissingMethodInvocationException;
+import org.mockito.exceptions.misusing.NotAMockException;
+import org.mockito.exceptions.misusing.NullInsteadOfMockException;
+import org.mockito.exceptions.misusing.PotentialStubbingProblem;
+import org.mockito.exceptions.misusing.RedundantListenerException;
+import org.mockito.exceptions.misusing.UnfinishedMockingSessionException;
+import org.mockito.exceptions.misusing.UnfinishedStubbingException;
+import org.mockito.exceptions.misusing.UnfinishedVerificationException;
+import org.mockito.exceptions.misusing.UnnecessaryStubbingException;
+import org.mockito.exceptions.misusing.WrongTypeOfReturnValue;
```
Comment (ming13) [inline src/main/java/org/mockito/internal/exceptions/Reporter.java]: Not sure if it follows the convention since the `*` was used before and `java.*` imports were listed below.

File: src/main/java/org/mockito/internal/exceptions/Reporter.java [hunk 2]
```diff
@@ -358,63 +370,70 @@ public static MockitoAssertionError wantedButNotInvokedInOrder(DescribedInvocati
         ));
     }
 
-    public static MockitoAssertionError tooManyActualInvocations(int wantedCount, int actualCount, DescribedInvocation wanted, Location firstUndesired) {
-        String message = createTooManyInvocationsMessage(wantedCount, actualCount, wanted, firstUndesired);
+    public static MockitoAssertionError tooManyActualInvocations(int wantedCount, int actualCount, DescribedInvocation wanted, List<Location> invocations) {
```
Comment (ming13) [inline src/main/java/org/mockito/internal/exceptions/Reporter.java]: `invocations` → `locations`?

File: src/main/java/org/mockito/internal/exceptions/Reporter.java [hunk 3]
```diff
@@ -358,63 +370,70 @@ public static MockitoAssertionError wantedButNotInvokedInOrder(DescribedInvocati
...
-                "Never wanted here:",
-                new LocationImpl(),
-                "But invoked here:",
-                firstUndesired,
-                ""
+            wanted.toString(),
+            "Never wanted here:",
+            new LocationImpl(),
+            "But invoked here:",
+            createAllLocationsMessage(invocations)
```
Comment (ming13) [inline src/main/java/org/mockito/internal/exceptions/Reporter.java]: Indentation might have changed.

File: src/main/java/org/mockito/internal/exceptions/Reporter.java [hunk 4]
```diff
@@ -358,63 +370,70 @@ public static MockitoAssertionError wantedButNotInvokedInOrder(DescribedInvocati
...
-                                                            Location lastActualInvocation) {
-        String ending =
-                (lastActualInvocation != null) ? lastActualInvocation + "\n" : "\n";
+    private static String createAllLocationsMessage(List<Location> locations) {
+        if (locations == null) {
+            return "\n";
+        }
+        StringBuilder sb = new StringBuilder();
+        for (Location invocation : locations) {
+            sb.append(invocation).append("\n");
```
Comment (ming13) [inline src/main/java/org/mockito/internal/exceptions/Reporter.java]: `infocation` → `location`?

File: src/main/java/org/mockito/internal/exceptions/Reporter.java [hunk 5]
```diff
@@ -358,63 +370,70 @@ public static MockitoAssertionError wantedButNotInvokedInOrder(DescribedInvocati
...
-        String message = createTooLittleInvocationsMessage(discrepancy, wanted, lastActualLocation);
+    public static MockitoAssertionError tooLittleActualInvocations(org.mockito.internal.reporting.Discrepancy discrepancy, DescribedInvocation wanted, List<Location> allLocations) {
+        String message = createTooLittleInvocationsMessage(discrepancy, wanted, allLocations);
 
         return new TooLittleActualInvocations(message);
     }
 
-    public static MockitoAssertionError tooLittleActualInvocationsInOrder(org.mockito.internal.reporting.Discrepancy discrepancy, DescribedInvocation wanted, Location lastActualLocation) {
-        String message = createTooLittleInvocationsMessage(discrepancy, wanted, lastActualLocation);
+    public static MockitoAssertionError tooLittleActualInvocationsInOrder(org.mockito.internal.reporting.Discrepancy discrepancy, DescribedInvocation wanted, List<Location> allLocations) {
```
Comment (ming13) [inline src/main/java/org/mockito/internal/exceptions/Reporter.java]: `allLocations` → `locations`? At this point it not entirely consistent with other calls if I understand correctly.

File: src/test/java/org/mockito/internal/verification/checkers/NumberOfInvocationsInOrderCheckerTest.java [hunk 6]
```diff
@@ -27,6 +22,11 @@
 import org.mockito.invocation.Invocation;
 import org.mockitousage.IMethods;
 
+import static java.util.Arrays.asList;
+import static java.util.Collections.emptyList;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.mockito.Mockito.mock;
```
Comment (ming13) [inline src/test/java/org/mockito/internal/verification/checkers/NumberOfInvocationsInOrderCheckerTest.java]: Same thing with imports as above.

File: src/main/java/org/mockito/internal/exceptions/Reporter.java (hunk 1 above)
Comment (SeriyBg) [reply src/main/java/org/mockito/internal/exceptions/Reporter.java]: As I can see the import layouts that was used before violates the conventions that are described here: https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md#coding-style
Should I revert it or is it better to follow the conventions that are in the guide?

File: src/test/java/org/mockito/internal/verification/checkers/NumberOfInvocationsInOrderCheckerTest.java (hunk 6 above)
Comment (SeriyBg) [reply src/test/java/org/mockito/internal/verification/checkers/NumberOfInvocationsInOrderCheckerTest.java]: Here the imports also violates the described import layout

File: src/main/java/org/mockito/internal/exceptions/Reporter.java (hunk 2 above)
Comment (SeriyBg) [reply src/main/java/org/mockito/internal/exceptions/Reporter.java]: Done

File: src/main/java/org/mockito/internal/exceptions/Reporter.java (hunk 3 above)
Comment (SeriyBg) [reply src/main/java/org/mockito/internal/exceptions/Reporter.java]: Done

File: src/main/java/org/mockito/internal/exceptions/Reporter.java (hunk 4 above)
Comment (SeriyBg) [reply src/main/java/org/mockito/internal/exceptions/Reporter.java]: Done

File: src/main/java/org/mockito/internal/exceptions/Reporter.java (hunk 5 above)
Comment (SeriyBg) [reply src/main/java/org/mockito/internal/exceptions/Reporter.java]: Done

**Comment by SeriyBg** [comment]
Have fixed all the remarks except the imports, since I'm not sure that the previous layouts was the correct ones

**Comment by SeriyBg** [comment]
@mockitoguy Thanks! I can rebase these PR if there are conflicts with the `release/2.x`

File: src/test/java/org/mockito/internal/invocation/InvocationsFinderTest.java [hunk 7]
```diff
@@ -185,4 +185,12 @@ public void shouldFindPreviousInOrder() throws Exception {
         previous = InvocationsFinder.findPreviousVerifiedInOrder(invocations, context);
         assertSame(simpleMethodInvocationTwo, previous);
     }
+
+    @Test
+    public void shouldFindAllStackTraces() {
+        List<Location> all = InvocationsFinder.getAllLocations(invocations);
+        Assertions.assertThat(all).contains(simpleMethodInvocation.getLocation(), simpleMethodInvocationTwo.getLocation(), differentMethodInvocation.getLocation());
+
+        Assertions.assertThat(InvocationsFinder.getAllLocations(Collections.<Invocation>emptyList())).isEmpty();
```
Comment (TimvdLippe) [inline src/test/java/org/mockito/internal/invocation/InvocationsFinderTest.java]: Let's put this assert in a separate test

**Comment by SeriyBg** [comment]
@TimvdLippe thanks. Have fixed your remark and also rebased the PR on top of `2.x` branch.
