### PR TITLE
Fully register a class' ancestry for GenericMetadataSupport.

### LINKED ISSUE #497: DEEP_STUBS tries to mock final class
```
  	<dependency>
  		<groupId>org.mockito</groupId>
  		<artifactId>mockito-core</artifactId>
  		<version>1.10.19</version>
  		<scope>test</scope>
  	</dependency>
```

```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

```
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.RETURNS_DEEP_STUBS;
import static org.mockito.Mockito.mock;

import org.junit.Test;

public class MockitoBug {
  public interface Supplier<T> {
    public T get();
  }

  public interface StringSupplier extends Supplier<String> {}

  public interface InheritedSupplier extends StringSupplier {}

  @Test
  public void deepStubs() {
    StringSupplier mock = mock(StringSupplier.class, RETURNS_DEEP_STUBS);
    String s = mock.get();
    assertNull(s);
  }

  @Test
  public void inheritedDeepStubs() {
    InheritedSupplier mock = mock(InheritedSupplier.class, RETURNS_DEEP_STUBS);
    String s = mock.get();  // ClassCastException
    assertNull(s);
  }
}
```

```
java.lang.ClassCastException: org.mockito.internal.creation.cglib.ClassImposterizer$ClassWithSuperclassToWorkAroundCglibBug$$EnhancerByMockitoWithCGLIB$$322ebf6e cannot be cast to java.lang.String
	at MockitoBug.inheritedDeepStubs(MockitoBug.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I expect the behavior for `StringSupplier` and `InheritedSupplier` to be the same: return `null` for `get`. However, `InheritedSupplier` tries to return a mock `Object` for `get`.

### PR DESCRIPTION
**Pull request by JeffreyFalgout**
The old implemention would take a class X and consider all of its superclasses
and the interfaces implemented by X and the interfaces implemented by all of
its superclasses.

The new implementation also considers the superinterfaces of the interfaces
implemented by X and the superinterfaces of the interfaces implemented by its
superclasses.

Fixes #497

### CODE REVIEW

**Comment by bric3** [comment]
This looks interesting ! Thanks for the PR !
This piece of code is tricky at best.

**Comment by TimvdLippe** [comment]
This pull request requires a rebase to resolve the failing builds with OpenJDK6. Other than that this LGTM.

**Comment by JeffreyFalgout** [comment]
>This pull request requires a rebase to resolve the failing builds with OpenJDK6

Done

File: src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java [hunk 1]
```diff
@@ -62,6 +62,42 @@
      */
     protected Map<TypeVariable, Type> contextualActualTypeParameters = new HashMap<TypeVariable, Type>();
 
+    /**
+     * Registers the type variables for the given type and all of its superclasses and superinterfaces.
+     */
+    protected void registerAllTypeVariables(Type classType) {
+        if (!(classType instanceof Class || classType instanceof ParameterizedType)) {
```
Comment (TimvdLippe) [inline src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java]: Codecov complains about not testing this path. I don't think this line is required per https://github.com/JeffreyFalgout/mockito/blob/b4b5b0be26aaf6218cd5b8253faf03e2d116bdb8/src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java#L272-L273 which handles the `instanceof` checks in `inferFrom` which is the only method that uses the `FromParameterizedTypeGenericMetadataSupport`.

File: src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java [hunk 2]
```diff
@@ -62,6 +62,42 @@
...
+            typesToRegister.addAll(Arrays.asList(rawType.getGenericInterfaces()));
+        }
+    }
+
+    private Class<?> getRawType(Type clazz) {
+        if (clazz instanceof ParameterizedType) {
+            return getRawType(((ParameterizedType) clazz).getRawType());
+        } else if (clazz instanceof Class) {
+            return (Class<?>) clazz;
+        } else {
```
Comment (TimvdLippe) [inline src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java]: This else clause is always when `clazz instanceof Class` so this Exception is not required. See above comment.

File: src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java [hunk 3]
```diff
@@ -62,6 +62,42 @@
...
+            throw new IllegalArgumentException(clazz.toString());
```
Comment (ChristianSchwarz) [inline src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java]: @JeffreyFalgout 
- Can this really happen? If yes more error infos would be usefule? E.g. "Unable to determine the raw type of "+type.
- just a matter of style the `else` keywords can be removed

File: src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java (hunk 2 above)
Comment (ChristianSchwarz) [inline src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java]: @TimvdLippe Haha i commented about the same in just the same minute!

File: src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java (hunk 1 above)
Comment (JeffreyFalgout) [inline src/main/java/org/mockito/internal/util/reflection/GenericMetadataSupport.java]: Done.
