### PR TITLE
Fixed JUnit Jupiter parallel issue

### LINKED ISSUE #1630: Mockito JUnit Jupiter extension does not correctly support parallel test execution
Sorry for not being able to provide the required information, but we just noticed that the MockitoExtension (mockito-junit-jupiter 2.24.5) leads to spurious test failures (e.g. due to calls to mocks not being recorded) when using "junit.jupiter.execution.parallel.enabled=true" with surefire. Prior we used our much simpler MockitoExtension which works fine in the same situation:

```java
public class MockitoExtension implements Extension, TestInstancePostProcessor, AfterEachCallback {
   @Override
   public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
      MockitoAnnotations.initMocks(testInstance);
   }

   @Override
   public void afterEach(ExtensionContext extensionContext) throws Exception {
      Mockito.validateMockitoUsage();
   }
}
```

### PR DESCRIPTION
**Pull request by mockitoguy**
Fixes #1630

This fix improves Mockito JUnit Jupiter extension. However, it does not completely resolve all kinds of parallel issues when nested test classes are used. I'll open a separate ticket for it.

### CODE REVIEW

File: subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java [hunk 1]
```diff
@@ -190,16 +196,24 @@ public void beforeEach(final ExtensionContext context) {
     private void collectParentTestInstances(ExtensionContext context, Set<Object> testInstances) {
         Optional<ExtensionContext> parent = context.getParent();
 
+        boolean firstParent = true;
```
Comment (TimvdLippe) [inline subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java]: Instead of having a boolean here, can we pass in `context.getParent()` on line 164. E.g. we pass the first parent in already, but then we keep all the other logic the same. That seems a little bit nicer to me and easier to follow. The comment can then be placed before line 164 instead.

Comment (mockitoguy) [reply subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java]: Please push a commit to this branch - it's simpler!

Comment (TimvdLippe) [reply subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java]: Sadly I am not at my working computer. I can do a push on Monday if you prefer.

Comment (mockitoguy) [reply subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java]: This works :-) Push on Monday. Have a nice weekend!

Comment (TimvdLippe) [reply subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java]: Done PTAL

**Comment by mockitoguy** [comment]
This is much nicer, thank you!!!
