### PR TITLE
Fixes #976: Resolve ambiguous constructors

### LINKED ISSUE #976: Make MockSettings.useConstructor able to choose the right constructor
## Use case

We recently added a very nice new feature #935 - ability to mock abstract classes / use real constructor for creating mocks. Currently we fail fast when multiple constructors are found matching provided arguments. However, Mockito could potentially do a better job identifying which constructor to use. Example scenario:

```java
class A {}
class B extends A {}
class C extends B {}

class Foo {
  Foo(A a) {};
  Foo(B b) {};
}

//Below fails with current implementation:
mock(Foo, withSettings().useConstructor(new A()));
mock(Foo, withSettings().useConstructor(new B()));
//However, we could make above work because the constructor argument are not really ambiguous

//Example use case of ambiguous constructor that we can remain failing on
mock(Foo, withSettings().useConstructor(new C()));
```

## Implementation

To get started, see CreatingMocksWithConstructorTest class. Unless the code changes, the interesting test method is [this one](https://github.com/mockito/mockito/blob/release/2.x/src/test/java/org/mockitousage/constructor/CreatingMocksWithConstructorTest.java#L150).

### PR DESCRIPTION
**Pull request by mureinik**
With the current code (introduced in Mockito 2.7.14 by commit 6a82c03), calling `MockSettings.useConstructor` with an argument list that would be applicable to more than one constructor would fail with an `org.mockito.internal.creation.instance.InstantiationException`.

This behavior, however, is suboptimal, as described in issue #976, as it makes `useConstructor` less robust than the Java compiler, which is able to resolve such ambiguities.
With this patch, Mockito will attempt to match the constructor with the most specific parameter types. A constructor X is considered more specific than a constructor Y if:

1. They are both applicable to the given argument list
2. Constructor X has at least one parameter which is a further specialization of the corresponding parameter of constructor Y (i.e. `paramX.isAssignableFrom(paramY)`).
3. Constructor Y has no parameter which is a further specialization of the corresponding parameter of constructor X, as defined above.

E.g., consider the following class:

    public class SomeClass {
        SomeClass(Object o) {}
        SomeClass(String s) {}
    }

Without this patch, calling

    mock(SomeClass.class, withSettings().useConstructor("string!"))

would fail. With this patch, such a call would invoke the `SomeClass(String)` constructor.

As noted above, this PR fixes issue #976.

### CODE REVIEW

**Comment by mureinik** [comment]
I wonder why Codecov has no previous report to compare against. Do any of the maintainers have a clue?

**Comment by TimvdLippe** [comment]
@mureinik Because commits by the delivery drone do `[ci skip]` and therefore do not trigger a code coverage report.

**Comment by mureinik** [comment]
@TimvdLippe That means that any PR that's rebased on top of a release won't have the benefit of a comparative CodeCov report. I get why the delivery drone should skip CI, but this is an unfortunate side effect. I'll bring this up on the mailing list - this PR probably isn't the right place to discuss it.

And thanks for the explanation!

**Comment by TimvdLippe** [comment]
@mureinik please see #493 for reference.

**Comment by mureinik** [comment]
@szczepiq ping? Will you have some time to take a look at this please?

**Comment by szczepiq** [comment]
@mureinik, I'm very keen to review this change. Thank you for your submission!

I'm allocating most of my time to https://github.com/mockito/mockito/issues/911 currently but I promise to review (and hopefully merge) by the end of this weekend.

Thanks for patience with us :)

**Comment by mureinik** [comment]
Rebased on top of 2.7.17 and added `CreatingMocksWithConstructorTest#can_spy_ambiguius_constructor_with_primitive` as per @TimvdLippe's suggestion above.

Note that this API does support implicit promotions (e.g., passing an `int` in `useConstructors()` varargs will autobox it to an `Integer`. This integer can't be matched to a constructor expecting a `long` primitive or a `Long` wrapper), in the same fashion that the `java.lang.reflect` APIs don't support it.

File: src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java [hunk 1]
```diff
@@ -130,4 +127,32 @@ private static boolean paramsMatch(Class<?>[] types, Object[] params) {
         }
         return true;
     }
+
+    private void evaluateConstructor(List<Constructor<?>> matchingConstructors, Constructor<?> constructor) {
```
Comment (szczepiq) [inline src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java]: Can you add a javadoc describing this method? It has non trivial complexity and it would be handy to understand why we are implementing the algorithm this way.

File: src/test/java/org/mockitousage/constructor/CreatingMocksWithConstructorTest.java [hunk 2]
```diff
@@ -137,45 +137,90 @@ public void exception_message_when_constructor_not_found() {
     static class ExtendsExtendsBase extends ExtendsBase {}
```
Comment (szczepiq) [inline src/test/java/org/mockitousage/constructor/CreatingMocksWithConstructorTest.java]: I love the new tests. Thank you for adding comprehensive coverage!!!

File: src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java [hunk 3]
```diff
@@ -107,10 +107,7 @@ private String constructorArgsString() {
     private InstantiationException multipleMatchingConstructors(Class<?> cls, List<Constructor<?>> constructors) {
         return new InstantiationException(join("Unable to create instance of '" + cls.getSimpleName() + "'.",
                 "Multiple constructors could be matched to arguments of types " + constructorArgTypes() + ":",
-                join("", " - ", constructors),
-                "If you believe that Mockito could do a better join deciding on which constructor to use, please let us know.",
-                "Ticket 685 contains the discussion and a workaround for ambiguous constructors using inner class.",
-                "See https://github.com/mockito/mockito/issues/685"
+                join("", " - ", constructors)
```
Comment (szczepiq) [inline src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java]: Let's keep the extra information. I think it is useful to:
 - inform about the inner class pattern for working around the ambiguous constructors
 - ask for feedback - it does not hurt to do that

You can keep the original or modify it if you want. I'd like to keep at least the hint about inner class.

Comment (mureinik) [inline src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java]: I originally took this message as a "workaround" until this PR is implemented, but you're right, let's keep it. Note there's a typo there ("join" instead of "job"). I'll fix that while I'm at it.

File: src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java (hunk 1 above)
Comment (mureinik) [inline src/main/java/org/mockito/internal/creation/instance/ConstructorInstantiator.java]: Good point, thanks.
I'll add some javadoc to explain this.

**Comment by mureinik** [comment]
Pushed updated branch. Change from previous push:

- Returned the error message regarding issue #685, as per @szczepiq review above
- Fixed a Freudian slip in the aforementioned error message ("a better **join**" -> "a better **job**")
- Added javadoc explaining the logic of `org.mockito.internal.creation.instance.ConstructorInstantiator#evaluateConstructor`, as per @szczepiq  review.

**Comment by mureinik** [comment]
The build failure seems to be a TravisCI issue, not an issue with the code itself, as this revision introduced only minor changes (added javadoc and fixed a typo) compared to the previous one, and some of the Travis checks are passing. 

The error:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

@szczepiq @TimvdLippe Is there any way to re-trigger Travis on this PR?

**Comment by TimvdLippe** [comment]
I have restarted the builds
