### PR TITLE
Fixes #2331

### LINKED ISSUE #2331: Spy doesn't forward hashcode/equals to actual object
### Mockito 3.11.1

```
public class MockitoTest {

    private static class ValueHolder {
        private final String value;

        public ValueHolder( String value ) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override public boolean equals( Object o ) {
            if (this == o) return true;
            if (!(o instanceof ValueHolder)) return false;
            ValueHolder that = (ValueHolder) o;
            return getValue().equals( that.getValue() );
        }

        @Override
        public int hashCode() {
            return Objects.hash( getValue() );
        }
    }

    @Test
    public void test() {
        ValueHolder value = new ValueHolder( "test" );
        ValueHolder spy = Mockito.spy( value );
        assert value.equals( spy );
        assert spy.equals( value ); //fails
        assert value.hashCode() == spy.hashCode(); //fails
    }
}
```

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by saurabh7248**
Has conditionally on basis of whether default answer is pass to actual methods made hash code and equals pass to actual methods.

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

File: src/main/java/org/mockito/internal/invocation/InvocationMatcher.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ public String toString() {
 
     @Override
     public boolean matches(Invocation candidate) {
-        return invocation.getMock().equals(candidate.getMock())
+        return invocation.getMock() == candidate.getMock()
```
Comment (TimvdLippe) [inline src/main/java/org/mockito/internal/invocation/InvocationMatcher.java:80]: I am not sure if I follow why this line was changed. Could you elaborate as to why?

**Review by TimvdLippe — APPROVED** [review]
It's not ideal to have another branch, but I think it is the best way forward. Only 1 question, but the rest LGTM

File: src/main/java/org/mockito/internal/invocation/InvocationMatcher.java (hunk 1 above)
Comment (saurabh7248) [reply src/main/java/org/mockito/internal/invocation/InvocationMatcher.java:80]: Consider the test PartialMockingWithSpiesTest.shouldAllowStubbingOfMethodsThatDelegateToOtherMethods.
Now the call to getName is handled by MockMethodInterceptor.DispatcherDefaultingToRealMethod.
interceptSuperCallable here the interceptor will not be null and it will go to interceptor.doIntercept. This finally leads to InvocationMatcher.matches

Now with changes in this pull request the call to equals is again delegated to  MockMethodInterceptor.DispatcherDefaultingToRealMethod and it will come at same place. And this way it leads to stackoverflow. Earlier equals of mock was this==that. So i just replced equals with ==.

Comment (TimvdLippe) [reply src/main/java/org/mockito/internal/invocation/InvocationMatcher.java:80]: Awesome, thanks for the explanation! That makes sense to me 😄

Comment (saurabh7248) [reply src/main/java/org/mockito/internal/invocation/InvocationMatcher.java:80]: Haha Thanks. Had missed to put links to the classes.
