### PR TITLE
Fixes #1254 and #1256: improved check for self-invocation.

### LINKED ISSUE #1254: Wanted but not invoked on 2.12.0, but not on 2.11.0
After updating Mockito from 2.11.0 to 2.12.0 the following test fails with `Wanted but not invoked`.

The weird thing is this happens only when running tests using Gradle. Android Studio runs the same test as successful. Just like #1183.

```java
package package.redacted;

import org.junit.Test;
import org.mockito.Mockito;

public class ViewModelTest {

    class View {
        private Runnable actionCallback = null;

        void callAction(Runnable callback) {
            actionCallback = callback;
        }

        void simulateActionCalled() {
            if (actionCallback != null) {
                actionCallback.run();
            }
        }

        void showResult() {
        }
    }

    class ViewModel {

        public ViewModel(final View view) {
            view.callAction(new Runnable() {
                @Override
                public void run() {
                    view.showResult();
                }
            });
        }
    }

    @Test public void test() {
        View view = Mockito.spy(new View());
        ViewModel viewModel = new ViewModel(view);

        view.simulateActionCalled();

        Mockito.verify(view).showResult();
    }
}
```
```
Wanted but not invoked:
view.showResult();
-> at package.redacted.ViewModelTest$View.showResult(ViewModelTest.java:22)

However, there were exactly 2 interactions with this mock:
view.callAction(
    package.redacted.ViewModelTest$ViewModel$1@26645040
);
-> at package.redacted.ViewModelTest$ViewModel.<init>(ViewModelTest.java:28)

view.simulateActionCalled();
-> at package.redacted.ViewModelTest.test(ViewModelTest.java:41)


	at package.redacted.ViewModelTest$View.showResult(ViewModelTest.java:22)
	at package.redacted.ViewModelTest.test(ViewModelTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

### LINKED ISSUE #1256: Unbounded recursion when spying with `mockito-inline`
Consider the following code:
```java
@Test
public void test() {
    ConcurrentMap<String, String> map = spy(new ConcurrentHashMap<>());
    map.putIfAbsent("a", "b");
}
```

Running it causes a `StackOverflowError`:
```
Configuring TestNG with: TestNG60Configurator
Exception in thread "TestNG-test=Surefire test-1" java.lang.StackOverflowError
        at org.mockito.internal.creation.bytebuddy.MockMethodDispatcher.get(MockMethodDispatcher.java:20)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:74)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:261)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:116)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:121)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:74)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:261)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:116)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:121)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        ...
```

Tested with Mockito 2.11.0 and 2.12.0. Do not happen if I disable `mockito-inline`. CC @raphw.

### PR DESCRIPTION
**Pull request by raphw**
Better checks for recursive calls and guards internally used JDK types.

Fixes #1254 
Fixes #1256

### CODE REVIEW

File: subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+        verify(d).bar(eq("baz"));
+    }
+
+    static class Dummy {
+
+        public void foo() {
+            bar("baz");
+        }
+
+        // Also fails if public.
```
Comment (Stephan202) [inline subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java]: With the issue fixed, this comment is no longer true. Would leave it out to avoid head-scratching.

Comment (raphw) [reply subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java]: Indeed, poorly copy-pasted. Thanks.

File: src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java [hunk 2]
```diff
@@ -45,6 +47,13 @@
     public MockMethodAdvice(WeakConcurrentMap<Object, MockMethodInterceptor> interceptors, String identifier) {
         this.interceptors = interceptors;
         this.identifier = identifier;
+        try {
+            Field field = WeakConcurrentMap.class.getDeclaredField("target");
```
Comment (mockitoguy) [inline src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java]: Can you add a code comment explaining why we need this? Please make it thorough, it would be great to share understanding! :)

File: src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java [hunk 3]
```diff
@@ -45,6 +47,13 @@
...
+            field.setAccessible(true);
+            backingMap = field.get(interceptors);
+        } catch (Exception e) {
+            throw new MockitoException("Could not resolve backing map from concurrent hash map", e);
```
Comment (mockitoguy) [inline src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java]: Can we make the message more actionable? Is there anything the user can do? File a ticket?

File: subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+ */
+package org.mockitoinline;
+
+import org.junit.Test;
+
+import static org.mockito.ArgumentMatchers.eq;
+import static org.mockito.Mockito.spy;
+import static org.mockito.Mockito.verify;
+
+public final class SuperCallTest {
```
Comment (mockitoguy) [inline subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java]: Nice test coverage!

I'm wondering if we should rather put the inline tests in main mockito codebase. The use cases should work for every Mockito mock maker, inline or not. We do run all our tests with inline mock as far as I remember.

Comment (raphw) [reply subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java]: Do we? I would not recall that. If so, yes, we should probably move the class.

File: src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java (hunk 3 above)
Comment (raphw) [reply src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java]: It is my library, I can add a method to get hold of the object. But I think we are safe here as we shade the code, no real danger here.

File: src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java (hunk 2 above)
Comment (raphw) [reply src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java]: Added a comment.

File: src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java (hunk 3 above)
Comment (raphw) [reply src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodAdvice.java]: Nevermind, we do of course inline it and can therefore change the code.

**Comment by raphw** [comment]
Updated the PR-

File: subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java (hunk 1 above)
Comment (Stephan202) [reply subprojects/inline/src/test/java/org/mockitoinline/SuperCallTest.java]: ^ The comment is still there ;).

**Comment by raphw** [comment]
I have merged this after your feedback which I took into consideration. If you have anything further, I am happy to adress it, I wanted to get this out as it affects a bunch of Kotlin users.

**Comment by mockitoguy** [comment]
Great! Thank you for merging!
