### PR TITLE
JUnit rules report unused stubs - fixes #384

### LINKED ISSUE #384: JUnit rule logs warnings about unsued / misused stubs
### Why

When test fails, the failure might be caused by misused stubs. Hence, it might be worth to log out debugging information to the System out (e.g. misused stubs, unused stubs).

### Plan

- [ ] document 2.x change
- [x] tweak the warning message
- [ ] add behavior to the runner
- [ ] add silent runner
- [ ] add silent setting to the rule (or warnings level for all / exception only / none)
- [ ] deprecate/remove console spamming runner

### Impl

The JUnit rule or the runner will potentially include following info in the output (somehow): https://gist.github.com/szczepiq/38619fd8766c66c46dff4dc2b6db06ec

I'm wondering if "Mockito.validateMockitoUsage();" should automatically print warnings. We could provide boolean parameter to control printing of the warnings.

### PR DESCRIPTION
**Pull request by szczepiq**
- Makes JUnit rules detect unused stubs
- Introduces MockitoListener API
- See the use case in issue #384 
- Recreated PR #527 with squashed commits

### CODE REVIEW

**Comment by szczepiq** [comment]
Let's merge this today. This PR is a squash of #527 plus some code changes per code review feedback (I addressed code feedback subjectively and selectively :).

File: src/main/java/org/mockito/internal/runners/UnnecessaryStubbingsReporter.java [hunk 1]
```diff
@@ -45,13 +47,20 @@ public void report(Class<?> testClass, RunNotifier notifier) {
...
         }
 
         if (stubbings.isEmpty()) {
             return;
         }
 
+        if (stubbings.isEmpty()) {
+            return; //whoa!!! All stubbings were used!
+        }
+
```
Comment (bric3) [inline src/main/java/org/mockito/internal/runners/UnnecessaryStubbingsReporter.java]: Comments in #527 not fixed

Comment (szczepiq) [inline src/main/java/org/mockito/internal/runners/UnnecessaryStubbingsReporter.java]: Ah, missed that. I'll fix it with next PR.
