### PR TITLE
Fix #1346 - Different mocks are used for @Mock and @InjectMock in the same test class with JUnit 5 extension

### LINKED ISSUE #1346: Different mocks are used for @Mock and @InjectMock in the same test class with JUnit 5 extension
I've been playing with the new JUnit 5 support in Mockito 2.17.0. I have found that with `@Mock` and `@InjectMocks` used in the same test class different mocks are injected. I would expect to have the same mock reused (as it works with JUnit 4 or manual `@Mock` initialization).

Sample code:
```
@ExtendWith(MockitoExtension.class)
public class SpaceShip5BugMiniTest {

    @InjectMocks
    private SpaceShip spaceShip;

    @Mock
    private TacticalStation tacticalStation;

    @Test
    public void shouldInjectMocks() {
        assertThat(tacticalStation).isNotNull();
        assertThat(spaceShip.getTacticalStation()).isEqualTo(tacticalStation);  
        //Bug ↑ - different mocks are use in @Mock and @InjectMock
    }
}
```

Error message:
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"tacticalStation (TacticalStation$MockitoMock$991606095@61d6015a)">
to be equal to:
 <"tacticalStation (TacticalStation$MockitoMock$991606095@b62d79)">
but was not.
Expected :tacticalStation
Actual   :tacticalStation
```

The minimal (non-)working example is available [here](https://github.com/szpak/code-examples-and-poc/tree/mockito2junit5-bug/mockito2-junit5).

@TimvdLippe Do you have an idea what could be wrong?

Mockito 2.17.0 (2.17.1 is not being released due to (https://github.com/mockito/shipkit/issues/679), junit-jupiter 5.1.0, OpenJDK 1.8.0_161, Linux.

### Checklist:
 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by SeriyBg**
Fix #1346 - fix `MockitoExtension` which has init mocks with two identical test instances which cause the mock to be initialized and injected two times

### CODE REVIEW

File: subprojects/junit-jupiter/src/test/java/org/mockitousage/JunitJupiterTest.java [hunk 1]
```diff
@@ -70,4 +73,17 @@ void shouldWeCreateMocksInTheParentContext() {
             assertThat(rootMock).isNotNull();
         }
     }
+
+    @Test
+    void should_be_injected_correct_instance_of_mock() {
+        assertThat(classWithDependency.dependency).isEqualTo(rootMock);
```
Comment (TimvdLippe) [inline subprojects/junit-jupiter/src/test/java/org/mockitousage/JunitJupiterTest.java]: Lets use `isSame` here, as we literally want this object to be there.

Comment (SeriyBg) [reply subprojects/junit-jupiter/src/test/java/org/mockitousage/JunitJupiterTest.java]: Good catch, have changed it. Thanks!

Comment (SeriyBg) [reply subprojects/junit-jupiter/src/test/java/org/mockitousage/JunitJupiterTest.java]: I have amended the previous commit as it's a simple and small change

**Comment by davinkevin** [comment]
Sadly, this doesn't cover the case where we are using `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`

> https://github.com/mockito/mockito/issues/1437
