### PR TITLE
Fixes #3331 : Fix `AdditionalMatchers.and()` and `AdditionalMatchers.or()` not to swap the order of matchers

### LINKED ISSUE #3331: AdditionalMatchers.and() and or() swap matcher order
Consider the following code:

```java
@ExtendWith(MockitoExtension.class)
public class MockitoTest {
  @Mock MyService myService;

  @Test
  public void test() {
    Mockito.when(
            myService.doSomething(
                and(any(MyPojo.class),
                    argThat(p -> p.id == 1))))
        .thenReturn(1);

    myService.doSomething("hello");
  }

  interface MyService {
    int doSomething(Object pojo);
  }

  static class MyPojo {
    int id = 1;
  }
}

```

This test throws the following exception:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class MockitoTest$MyPojo (java.lang.String is in module java.base of loader 'bootstrap'; MockitoTest$MyPojo is in unnamed module of loader 'app')
	at org.mockito.internal.matchers.And.matches(And.java:23)
	at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:35)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.argsMatch(MatcherApplicationStrategy.java:85)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:71)
	at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:156)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:82)
	at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:92)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:161)
	at MockitoTest$MyService$MockitoMock$v3DeXXsQ.doSomething(Unknown Source)
	at MockitoTest.test(MockitoTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

Debugger inspection of [`And.matches()`](https://github.com/mockito/mockito/blob/fb9ff6d40442ea98c8c3f8bc9fffbe253bd8df7b/src/main/java/org/mockito/internal/matchers/And.java#L22) shows that `m1` is the lambda and `m2` is the `InstanceOf`, as opposed to what was passed to `and()`. I guess this comes from [`ArgumentMatcherStorageImpl#reportAnd()` and `reportOr()`](https://github.com/mockito/mockito/blob/fb9ff6d40442ea98c8c3f8bc9fffbe253bd8df7b/src/main/java/org/mockito/internal/progress/ArgumentMatcherStorageImpl.java#L42-L59) which pop `m1` before `m2`, swapping the order.

This is with Mockito 5.11.0, Junit 5.10.2 and Java 11.

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
    _No, it does not provide useful information (here the exception is similar to the one in #2268 but it could be something else like an NPE, depending on the use case)_
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by dev-jonghoonpark**
related issue: #3331

### Motivation:
- On #3331, we found that AdditionalMatchers.and() and or() swap matcher order

### Modification:
- Changed the assignment order of `popMatcher()` results.

### Result:
- Now, AdditionalMatchers.and() and or() not swap matcher order
- Close #3331

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

File: src/test/java/org/mockito/internal/progress/ArgumentMatcherStorageImplTest.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+package org.mockito.internal.progress;
+
+import org.junit.Before;
+import org.junit.Test;
+import org.mockito.internal.matchers.InstanceOf;
+import org.mockitoutil.TestBase;
+
+import static org.junit.Assert.assertEquals;
+
+public class ArgumentMatcherStorageImplTest extends TestBase {
```
Comment (TimvdLippe) [inline src/test/java/org/mockito/internal/progress/ArgumentMatcherStorageImplTest.java:14]: Instead of a test that tests the internals, please create a regression test in `src/test/java/org/mockitousage` where you copy the example in the issue description of #3331 That way, we test against the user code, rather than how Mockito itself is built.

**Review by TimvdLippe — CHANGES_REQUESTED** [review]

File: src/test/java/org/mockito/internal/progress/ArgumentMatcherStorageImplTest.java (hunk 1 above)
Comment (dev-jonghoonpark) [reply src/test/java/org/mockito/internal/progress/ArgumentMatcherStorageImplTest.java:14]: @TimvdLippe 

Thank you for your reply.

Could you please check if I understand correctly?

- Move the test under `src/test/java/org/mockitousage`.
- Modify it so that it does not test against the code inside mockito, but against the user's code (black box testing).

**Comment by dev-jonghoonpark** [comment]
@TimvdLippe 

I midified the code based on your feedback, can you check it?

The test code works like this

## and
- If the test is sequential, it will be filtered out by`any(String.class)`, so `doSomeThing()` will not return 1.
- If it's not sequential, the test will fail with an error in `argThat(String::isEmpty)`. (because the input is not a String)

## or
- If the test is sequential, `any(Integer.class)` will pass, so `doSomeThing()` will return 1.
- If it is not sequential, the test will fail with an error in `argThat(String::isEmpty)`. (because the input is not a String)

**Review by TimvdLippe — APPROVED** [review]
This looks great, thank you so much!

**Comment by dev-jonghoonpark** [comment]
I'll check why the test is failing and fix it. ; )

**Comment by TimvdLippe** [comment]
You can run `./gradlew spotlessApply` to automatically fix it for you.
