### PR TITLE
Fixes #2497: Throw exception on invalid matchers for `mockStatic`

### LINKED ISSUE #2497: ArgumentMatchers not working for Mockito.mockStatic
When I do a mockStatic with argument matchers like this:

```
var mockedRequestClass = Mockito.mockStatic(RequestClass.class);
mockedRequestClass.when(() -> RequestClass.sendRequest(mockedUrl, any(), any())).thenReturn(null);
```

Mockito throws the following exception:
`org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.`

How can I use argument matchers with Mockito.mockStatic? Shouldn't that be possible?

### PR DESCRIPTION
**Pull request by temp-droid**
I'm not sure if the `Throwable` catch block can be removed so I decided to keep it for now. Feel free to mention if it can be deleted.

I didn't follow the "snake case convention" for the test method to be consistent with the other test methods of the file, but I'm fine changing it.

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

File: subprojects/inline/src/test/java/org/mockitoinline/StaticMockTest.java [hunk 1]
```diff
@@ -20,6 +23,9 @@
 
 public final class StaticMockTest {
 
+    @Rule
+    public ExpectedException exception = ExpectedException.none();
```
Comment (TimvdLippe) [inline subprojects/inline/src/test/java/org/mockitoinline/StaticMockTest.java:27]: Rather than this rule, let's keep it consistent with the rest of the codebase and use `assertj`. Then we can wrap the statement that we expect to fail, without letting it fail the whole method.

**Review by TimvdLippe — CHANGES_REQUESTED** [review]
Nice and easy fix! I am not actually sure why we swallow exceptions here, but this is probably the safest change we can make. Only 1 nit with using assertj for more precise assertions.

File: subprojects/inline/src/test/java/org/mockitoinline/StaticMockTest.java (hunk 1 above)
Comment (TimvdLippe) [reply subprojects/inline/src/test/java/org/mockitoinline/StaticMockTest.java]: Ah yes makes sense. I filed #2510 for us to clean up `ExpectedException` and will clean some up today. Thanks for the fix!

**Review by TimvdLippe — APPROVED** [review]
