### PR TITLE
Pretty print primitive and wrappers types in Maps

### LINKED ISSUE #570: Hard to understand argument difference between int and long
check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

JDK: 1.8
OS: linux
mockito: master branch

Sample code:

```
package com.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.runners.MockitoJUnitRunner;

import java.util.HashMap;
import java.util.Map;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

public class HogeTest {
    @Test
    public void test() {
        Hello hello = mock(Hello.class);
        hello.greeting(new HashMap<String, Object>() {{
            put("hello", 3L);
        }});
        verify(hello).greeting(new HashMap<String, Object>() {{
            put("hello", 3);
        }});
    }

    public static class Hello {
        void greeting(Map<String, Object> l) {
        }
    }
}
```

Output:
```
Testing started at 8:37 AM ...
8:37:01 AM: Executing external tasks ':cleanTest :test --tests "com.example.HogeTest.test"'...
:cleanTest
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
com.example.HogeTest > test FAILED
    org.mockito.exceptions.verification.junit.ArgumentsAreDifferent at HogeTest.java:31


Argument(s) are different! Wanted:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:31)
Actual invocation has different arguments:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:26)

Argument(s) are different! Wanted:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:31)
Actual invocation has different arguments:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:26)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.example.HogeTest.test(HogeTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

1 test completed, 1 failed
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/tokuhirom/dev/mockito-sample/build/reports/tests/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1.713 secs
There were failing tests. See the report at: file:///Users/tokuhirom/dev/mockito-sample/build/reports/tests/index.html
```

In this case, user can't understand the difference between _wanted_ and _actual_. Since 2 dumps are same!

```
Argument(s) are different! Wanted:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:31)
Actual invocation has different arguments:
hello.greeting(() {hello=3});
-> at com.example.HogeTest.test(HogeTest.java:26)
```

If there's a *L* suffix for long value, user can understand the difference.

### PR DESCRIPTION
**Pull request by tokuhirom**
check list

 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

In following case, user can't understand the difference between expected and actual.

Code:

    @Test
    public void foo() {
        Foo m = mock(Foo.class);
        m.foo(new HashMap<String, Object>(){{
            put("hoge", 4);
        }});
        verify(m).foo(new HashMap<String, Object>(){{
            put("hoge", 4L);
        }});
    }

    public static class Foo {
        void foo(Map<String, Object> map) {
        }
    }

Output:

    Argument(s) are different! Wanted:
    foo.foo(() {hoge=4});
    -> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    Actual invocation has different arguments:
    foo.foo(() {hoge=4});
    -> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

If mockito outputs the "L" suffix for long values, user can understand the difference easily.

After this commit, the output will be following:

    Argument(s) are different! Wanted:
    foo.foo({"hoge"=4L});
    -> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    Actual invocation has different arguments:
    foo.foo({"hoge"=4});
    -> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

This will fix #570

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@tokuhirom For this change to work, some existing test have to be updated. See https://travis-ci.org/mockito/mockito/jobs/153725521 for details.

**Comment by tokuhirom** [comment]
Oops. I forget to fix these test cases. Fixed commit, squash it, and force pushed.

File: src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java [hunk 1]
```diff
@@ -14,7 +16,14 @@ public void prints_values() throws Exception {
...
         assertEquals("\"str\"", print("str"));
         assertEquals("\"x\ny\"", print("x\ny"));
+        assertEquals("3", print(3));
+        assertEquals("3L", print(3L));
         assertEquals("[1, 2]", print(new int[]{1, 2}));
+        assertEquals("{\"hoge\"=2L}", print(new HashMap<String, Object>() {
+            {
+                put("hoge", 2L);
+            }
+        }));
```
Comment (TimvdLippe) [inline src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java]: Also add an assert for multiple values in a hashmap.

**Comment by TimvdLippe** [comment]
One small comment regarding testing. Are floats prettyprinted too? (I cant test right now because on mobile)

**Comment by ChristianSchwarz** [comment]
Currently only Long is pretty printed. The types Float,Double,Byte,Short are not.

File: src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java (hunk 1 above)
Comment (TimvdLippe) [inline src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java]: Probably for multiple values it would be good to add some white-space around the `=` and maybe put them on a new-line.

Comment (tokuhirom) [inline src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java]: Added test case for mutliple values in a hashmap.

Comment (tokuhirom) [inline src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java]: And, added white-spaces around the '='

**Comment by tokuhirom** [comment]
Pretty print double and float values.
But I guess there's no byte/short literal in Java language. What's format is better?

File: src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java [hunk 2]
```diff
@@ -14,7 +16,22 @@ public void prints_values() throws Exception {
         assertEquals("null", print(null));
         assertEquals("\"str\"", print("str"));
         assertEquals("\"x\ny\"", print("x\ny"));
+        assertEquals("3", print(3));
+        assertEquals("3L", print(3L));
+        assertEquals("3.14d", print(3.14d));
+        assertEquals("3.14f", print(3.14f));
         assertEquals("[1, 2]", print(new int[]{1, 2}));
+        assertEquals("{\"hoge\" = 2L}", print(new LinkedHashMap<String, Object>() {
```
Comment (ChristianSchwarz) [inline src/test/java/org/mockito/internal/matchers/text/ValuePrinterTest.java]: @tokuhirom 
for better readability better use [Collections.singletonMap(K,V)](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#singletonMap(K,%20V)) here

**Comment by ChristianSchwarz** [comment]
I wonder if it is possible to add a type literal postfix only for Maps. Otherwise we have infomation duplication in other cases e.g.:

```
mock.withLongAndInt(100, 200);
verify(mock).withLongAndInt(eq(100), eq(200));
```
This throws an ArgumentsAreDifferent containing "withLongAndInt((Long) 100L, 200)"

**Comment by bric3** [comment]
> But I guess there's no byte/short literal in Java language. What's format is better?

@tokuhirom Indeed, I would forget about the shorts, as they are rarely used anyway. However for bytes what do you think of printing then as hexadecimal or binary :

```java
(byte) 0x1A // 26
(byte) 0b11010 // 26
```

I'd prefer hex, it is shorter. I think the cast instruction is important for that one, because hex or binary literal are not automatically casted on a call site (it is only on a variable / field declaration).

**Comment by bric3** [comment]
@tokuhirom By the way thanks for the PR !

**Comment by bric3** [comment]
@ChristianSchwarz Indeed `withLongAndInt((Long) 100L, 200)` seems redundant. We can remove the cast if it is not relevant there.

**Comment by TimvdLippe** [comment]
@tokuhirom Changes look good! I think now only `Byte` and `Short` are required and then we can merge :tada:

**Comment by bric3** [comment]
@TimvdLippe let's forget short, there's no notation for short literals in the language

**Comment by TimvdLippe** [comment]
Oh sorry, I completely missed your previous comment regarding hex notation. Yes agreed we can ditch Short and state Byte in hex.

**Comment by ChristianSchwarz** [comment]
Do you really want to format all bytes as hex? I think a hex presentation make only sense in scenarios were you do e.g. low level stuff. And how can a user determine the type of 0xA3, is it a byte or a short?

**Comment by bric3** [comment]
@ChristianSchwarz That is why I prepended my examples with the cast instruction.
And yes hex is fine for a single byte.

Shorts will be represented as a numbers.

**Comment by tokuhirom** [comment]
@TimvdLippe okay, i added format for Byte type.

**Comment by TimvdLippe** [comment]
LGTM, thanks a lot @tokuhirom !

**Comment by ChristianSchwarz** [comment]
Okay this PR is closed, for the record here you can find the [symbols](http://docs.oracle.com/javase/6/docs/technotes/guides/jni/spec/types.html#wp276) defined in the java spec for all types:


|   Type Signature | Java Type   |
|---|---|
|Z | boolean|
|B|byte|
|C | char|
|S | short|
|I | int|
|J | long|
|F | float|
|D | double|

The type signature can be used to distingish primitive types. Maybe this is useful in the future when ppl, are confused by hex values ( remember 0xE2 is an `int` not `byte`) or can't distinguish int's from short's.

**Comment by bric3** [comment]
@ChristianSchwarz see #693
