### PR TITLE
Return completed futures for unstubbed Future/CompletionStage in ReturnsEmptyValues

### LINKED ISSUE #3724: Future<void> methods on mocks throw "type 'Null' is not a subtype of type   'Future<void>'"
When using mockito: ^5.0.0 with null safety, mocking a method that returns a
  Future<void> can lead to a type 'Null' is not a subtype of type 'Future<void>'
  error at runtime. This happens even when the method call is stubbed with
  thenAnswer((_) async => {}) or thenReturn(Future.value()). The only workaround
  is to create a fake implementation of the class instead of using a mock.

  Steps to reproduce:

   1. Create a class with a method that returns Future<void>.
   2. Create a mock of that class using class MockMyClass extends Mock implements
      MyClass {}.
   3. In a test, stub the method call on the mock to return a Future<void>.
   4. Call the method on the mock.

  Expected behavior:

  The method call should not throw an error.

  Actual behavior:

  A type 'Null' is not a subtype of type 'Future<void>' error is thrown.

### PR DESCRIPTION
**Pull request by Woongi9**
Fixes #3724 

Updated `ReturnsEmptyValues#returnValueFor` so that for return types
`Future`, `CompletableFuture`, and `CompletionStage`, Mockito now returns
`CompletableFuture.completedFuture(null)` instead of `null`.

### Tests
- Added `ReturnsEmptyValuesFutureTest` to verify the new default behavior:
  - `Future<String>` returns a completed future with `null` result.
  - `CompletableFuture<Void>` returns a completed future that can be joined without exceptions.
  - `CompletionStage<Integer>` returns a completed stage that can be safely chained.

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [ ] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style (run `./gradlew spotlessApply` for auto-formatting)
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should end with `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by Woongi9** [comment]
@TimvdLippe 
Reviews and feedback are welcome — I’ll be happy to fix anything needed.

File: mockito-core/src/test/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValuesFutureTest.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    interface ReturnCompletableFuture {
+        CompletableFuture<Void> v();
+    }
+
+    interface ReturnCompletionStage {
+        CompletionStage<Integer> s();
+    }
+
+    @Test
+    public void returnsCompletedFuture_forFuture() throws Exception {
```
Comment (TimvdLippe) [inline mockito-core/src/test/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValuesFutureTest.java:33]: These tests look good to me. Rather than a separate test suite, can you move them into `mockito-core/src/test/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValuesTest.java` instead?

**Review by TimvdLippe — CHANGES_REQUESTED** [review]
1 nit, the rest LGTM!

File: mockito-core/src/test/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValuesFutureTest.java (hunk 1 above)
Comment (Woongi9) [reply mockito-core/src/test/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValuesFutureTest.java]: Done, I’ve moved the tests into ReturnsEmptyValuesTest. Thanks for the review!

**Review by TimvdLippe — APPROVED** [review]
Thanks!

**Comment by honnix** [comment]
Looks like this is a breaking change, so maybe worth noting in the release notes (although the minor version bump might already indicate that).
