### PR TITLE
Fixes #548 from now on verification happens always call in other thre…

### LINKED ISSUE #548: VerificationWithTimeoutTest is unstable
See build failure: https://travis-ci.org/mockito/mockito/jobs/151406672

Full stack trace:

```
org.mockitousage.verification.VerificationWithTimeoutTest > shouldAllowTimeoutVerificationInOrder FAILED
    org.mockito.exceptions.verification.VerificationInOrderFailure: 
    Verification in order failure
    Wanted but not invoked:
    mock.oneArg('1');
    -> at org.mockitousage.verification.VerificationWithTimeoutTest.shouldAllowTimeoutVerificationInOrder(VerificationWithTimeoutTest.java:161)
    Wanted anywhere AFTER following interaction:
    mock.oneArg('x');
    -> at org.mockitousage.verification.VerificationWithTimeoutTest.shouldAllowTimeoutVerificationInOrder(VerificationWithTimeoutTest.java:155)
```

### PR DESCRIPTION
**Pull request by lukasz-szewc**
Should fix problems with #548 and #601

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I am going to restart this build a couple of times to test the robustness.

**Comment by lukasz-szewc** [comment]
It could take a  while. Hopefully we have loops.

In the meantime try this gist : https://gist.github.com/lukasz-szewc/f1ca9cece0a8997e898e5b6ba1a65f0c

**Comment by TimvdLippe** [comment]
Got a failed Travis job: https://travis-ci.org/mockito/mockito/jobs/156890987. The culprit seems to be `org.mockitousage.verification.VerificationAfterDelayTest > shouldVerifyNormallyWithSpecificTimes`

**Comment by lukasz-szewc** [comment]
I have not touched `VerificationAfterDelayTest` in this PR...

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java [hunk 1]
```diff
@@ -161,13 +193,47 @@ public void shouldAllowTimeoutVerificationInOrder() throws Exception {
...
+                executor.execute(runnable(countDownLatch, invocation));
+            }
+            countDownLatch.await();
+        }
+
+        private Runnable runnable(final CountDownLatch countDownLatch, final Character invocation) {
+            return new Runnable() {
+                @Override
+                public void run() {
+                    countDownLatch.countDown();
```
Comment (TimvdLippe) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: Shouldn't this statement be moved as last statement? If I read the docs correctly, `countDownLatch.await()` will proceed when all Threads have called `countDownLatch.countDown()`.

**Comment by TimvdLippe** [comment]
Yes I know, was merely stating that the Travis failure we experienced was a different test. Nonetheless, I think it is best if we aggregrate all test fixes in a PR to study the robustness. Would you be willing to do so?

**Comment by lukasz-szewc** [comment]
Yup, another commit with `VerificationAfterDelayTest` changes. Take a look.

**Comment by TimvdLippe** [comment]
Great thanks, will be restarting these changes a couple of times too. Really nice to have deterministic results now! :tada:

File: src/test/java/org/mockitousage/verification/DelayedExecution.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+            executor.execute(runnable(countDownLatch, invocation));
+        }
+        countDownLatch.await();
+    }
+
+    private Runnable runnable(final CountDownLatch countDownLatch, final Character invocation) {
+        return new Runnable() {
+            @Override
+            public void run() {
+                countDownLatch.countDown();
```
Comment (TimvdLippe) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: Adding my previous comment again:

Shouldn't this statement be moved as last statement? If I read the docs correctly, `countDownLatch.await()` will proceed when all Threads have called `countDownLatch.countDown()`.

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java (hunk 1 above)
Comment (lukasz-szewc) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: Yes and no.  :)

If I move it as a last line in run method then I guarantee that invocation on mock has been performed and in that case any time verification (later in test) is pretty pointless. It would not make a difference if the time slot is 1 millisecond or 1000 milliseconds. 

On the other hand, If I move the countDown before execution on mock (like it is proposed right now), then verification after some time makes sense because we are executing at least two activities in parallel.

File: src/test/java/org/mockitousage/verification/DelayedExecution.java (hunk 2 above)
Comment (lukasz-szewc) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: Yes and no. :)

If I move it as a last line in run method then I guarantee that invocation on mock has been performed and in that case any time verification (later in test) is pretty pointless. It would not make a difference if the time slot is 1 millisecond or 1000 milliseconds.

On the other hand, If I move the countDown before execution on mock (like it is proposed right now), then verification after some time makes sense because we are executing at least two activities in parallel.

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java (hunk 1 above)
Comment (bric3) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: @lukasz-szewc But the goal of the test is not to test these invocation but to test the timeout verification mode. So when we want to ensure calls have been finished before the verification is virtually OK.

Otherwise that was pretty much the idea I had in mind for timeout tests. And we can have the same kind of tricks for the after timeout.

**Comment by bric3** [comment]
I'm ok with the change. Even if the fact that async are not completely deterministic, it definitely an improvement, plus the test code is elegant!

File: src/test/java/org/mockitousage/verification/DelayedExecution.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+import java.util.concurrent.CountDownLatch;
+import java.util.concurrent.ScheduledExecutorService;
+
+class DelayedExecution {
+    private final ScheduledExecutorService executor;
+    private final IMethods mock;
+    private final int delay;
+    private final ArrayList<Character> invocations = new ArrayList<Character>();
+
+    public DelayedExecution(ScheduledExecutorService executor, IMethods mock, int delay) {
```
Comment (bric3) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: Could you add the TimeUnit parameter?

**Comment by bric3** [comment]
@lukasz-szewc Also after adding the `TimeUnit` parameter to `DelayedExection` ? Could rebase your commits (`added one missing line` is not really the most expressive message) ;)

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java [hunk 4]
```diff
@@ -137,21 +156,32 @@ public void shouldAllowMixingOnlyWithTimeoutAndFail() throws Exception {
...
+        delayedExecution.recordAsyncCall('2');
+
         // when
-        callAsyncWithDelay(mock, '0', 0, MILLISECONDS);
-        callAsyncWithDelay(mock, '1', 0, MILLISECONDS);
-        callAsyncWithDelay(mock, '2', 20, MILLISECONDS);
+        delayedExecution.allAsyncCallsStarted();
 
         // then
+        verify(mock, timeout(50)).oneArg('0');
```
Comment (ChristianSchwarz) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: @lukasz-szewc 
This line must be removed cause this was not tested in the original test case. For the same reason the call with '2' must be delayed by 20ms.

Comment (bric3) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: @ChristianSchwarz Good point. I overlooked this one thinking the countdown latch semantic forbid that, but there is two way to handle this 
* it's possible add a new instance of `DelayedExecution` and insert `allAsyncCallsStarted` before the last verify
* tweak the `DelayedExecution` API to be more fine grained

About the missing verify I noted it as well in the original test as well, but it may be de to a human error so I'm ok with the addition.

**Comment by ChristianSchwarz** [comment]
I like the idea of starting the threads and await there readiness, this might solve the timing issues. An other option is to write an simplified ScheduledExecutorService with the same behavior as the DelayedExecution of this PR. This way the test can remain untouched and we have still the possibiliy run tasks with individual delay as required by one test.

File: src/test/java/org/mockitousage/verification/DelayedExecution.java (hunk 3 above)
Comment (lukasz-szewc) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: I will

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java (hunk 4 above)
Comment (lukasz-szewc) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: I will keep original intent of that test. However this particular test is at least weird and I have no idea what this test is actually testing

**Comment by lukasz-szewc** [comment]
1. added `TimeUnit` to constructor
2. reworked one of test in `VerificationWithTimeoutTest' mentioned above
3. rebased and pushed with force

take a look.

File: src/test/java/org/mockitousage/verification/DelayedExecution.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+                countDownLatch.countDown();
+                sleep();
+                mock.oneArg(invocation.charValue());
+            }
+        };
+    }
+
+    private void sleep() {
+        try {
+            timeUnit.sleep(delay);
```
Comment (bric3) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: @lukasz-szewc Actually the idea of passing the TimeUnit is to do a `TimeUnit.toMillis(delay)` here ;)

File: src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java [hunk 6]
```diff
@@ -137,11 +157,14 @@ public void shouldAllowMixingOnlyWithTimeoutAndFail() throws Exception {
...
+        // given
+        DelayedExecution delayedExecution = createZeroMillisDelayedExecution();
+        DelayedExecution twentyMillisDelayedExecution = createTwentyMillisDelayedExecution();
+
         // when
-        callAsyncWithDelay(mock, '0', 0, MILLISECONDS);
-        callAsyncWithDelay(mock, '1', 0, MILLISECONDS);
-        callAsyncWithDelay(mock, '2', 20, MILLISECONDS);
+        delayedExecution.allAsyncCallsStarted();
+        twentyMillisDelayedExecution.allAsyncCallsStarted();
```
Comment (bric3) [inline src/test/java/org/mockitousage/verification/VerificationWithTimeoutTest.java]: @lukasz-szewc I'd rather propose

```java
delayedExecution.allAsyncCallsStarted();

verify(mock, timeout(50)).oneArg('1');
twentyMillisDelayedExecution.allAsyncCallsStarted();
verify(mock, timeout(50)).oneArg('2');
```

File: src/test/java/org/mockitousage/verification/DelayedExecution.java (hunk 5 above)
Comment (ChristianSchwarz) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: @bric3 @lukasz-szewc 
better use `timeUnit.sleep(delay)` here ;-)

Comment (bric3) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: That works too ;)

Comment (bric3) [inline src/test/java/org/mockitousage/verification/DelayedExecution.java]: I think I bugged there it's already `timeUnit.sleep(delay);`
