### PR TITLE
Fixes #731 Implements retry rule for flaky tests

### LINKED ISSUE #731: Consider rerunning failed tests
Consider rerunning failed tests to avoid https://travis-ci.org/mockito/mockito/jobs/172673452

Some options:
 - rerun test Gradle task
 - rerun test rule http://stackoverflow.com/questions/8295100/how-to-re-run-failed-junit-tests-immediately

### PR DESCRIPTION
**Pull request by bric3**
Previous attempts at fixing the time related tests failed. Indeed the previous attempts are not bullet proof when the CI can run schedule some threads slower than _expected_.

A proper harness should be implemented, but in the meantime, I implemented the retry rule as proposed in #731 to gain back stability on the build.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
The amount of import reordering and stylistic changes is quite high sadly. Would be nice to prevent these for new PRs

File: src/test/java/org/mockitoutil/RetryRule.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+                public void evaluate() throws Throwable {
+                    for (int remainingAttempts = attempts; remainingAttempts > 0 ; remainingAttempts--) {
+                        try {
+                            base.evaluate();
+                        } catch (Throwable throwable) {
+                            if (remainingAttempts > 0) {
+                                throw throwable;
+                            }
+                        }
+                    }
```
Comment (szpak) [inline src/test/java/org/mockitoutil/RetryRule.java]: For negative attempts defined by developer the code in the for loop will never be executed - no evaluation of a base statement will be performed which in turn may hide potential exceptions in a test.

**Comment by bric3** [comment]
> The amount of import reordering and stylistic changes is quite high sadly. Would be nice to prevent these for new PRs

Regarding the imports I followed the new style guide. To lower this noise, we can apply the style guide on the whole project. Also I think it's possible to export/import the IntelliJ/Eclipse style config.

File: src/test/java/org/mockitoutil/RetryRule.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+ */
+
+package org.mockitoutil;
+
+import org.junit.rules.TestRule;
+import org.junit.runner.Description;
+import org.junit.runners.model.Statement;
+
+public class RetryRule implements TestRule {
+    private TestRule innerRule;
```
Comment (bric3) [inline src/test/java/org/mockitoutil/RetryRule.java]: ok

File: src/test/java/org/mockitoutil/RetryRule.java (hunk 1 above)
Comment (bric3) [inline src/test/java/org/mockitoutil/RetryRule.java]: Added an `assert` check

**Comment by TimvdLippe** [comment]
@bric3 Yes it is good you enforce it, it's that others don't :P Seems like a good idea to fix it once and then block PRs if they change it.
